name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # la branche que tu utilises

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # la racine du dépôt, là où est index.html
